--liquibase formatted sql
--changeset igor_podg:1

CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    code VARCHAR(4) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS consulates (
    id SERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    country INTEGER NOT NULL REFERENCES countries(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS parameters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    value INTEGER NOT NULL,
    updated_at DATE NOT NULL DEFAULT NOW(),
    created_at DATE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS warnings (
    id SERIAL PRIMARY KEY,
    country INTEGER NOT NULL UNIQUE REFERENCES countries(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL
);
